# Generated by Django 3.2.5 on 2021-09-02 03:16

import database.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='blocks1',
        ),
        migrations.RemoveField(
            model_name='score',
            name='blocks2',
        ),
        migrations.RemoveField(
            model_name='score',
            name='blocks3',
        ),
        migrations.RemoveField(
            model_name='score',
            name='code1',
        ),
        migrations.RemoveField(
            model_name='score',
            name='code2',
        ),
        migrations.RemoveField(
            model_name='score',
            name='code3',
        ),
        migrations.AddField(
            model_name='score',
            name='blocks',
            field=database.models.IntegerListField(default=[-1, -1, -1], max_length=200),
        ),
        migrations.AddField(
            model_name='score',
            name='codes',
            field=database.models.CharListField(default=['', '', '']),
        ),
    ]
