# Generated by Django 3.2.7 on 2021-09-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='team',
        ),
    ]
