# Generated by Django 3.2.5 on 2021-09-02 03:17

import database.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210902_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='blocks',
            field=database.models.IntegerListField(default=[-1, -1, -1, -1], max_length=200),
        ),
        migrations.AlterField(
            model_name='score',
            name='codes',
            field=database.models.CharListField(default=['', '', '', '']),
        ),
    ]
