# Generated by Django 3.2.5 on 2021-09-02 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20210902_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='score',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
