# Generated by Django 3.2.5 on 2021-09-03 05:32

import database.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20210902_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='turtle',
            field=database.models.IntegerListField(default=[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], max_length=200),
        ),
        migrations.AddField(
            model_name='score',
            name='turtle_codes',
            field=database.models.CharListField(default=['', '', '', '', '', '', '', '', '', '', '']),
        ),
    ]
