# Generated by Django 3.2.5 on 2021-09-03 05:37

import database.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20210903_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='time2',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='score',
            name='turtle',
            field=database.models.IntegerListField(default=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], max_length=200),
        ),
    ]
