# Generated by Django 3.2.7 on 2021-09-03 15:15

import database.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20210903_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='movie',
            field=database.models.IntegerListField(default=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], max_length=200),
        ),
        migrations.AddField(
            model_name='score',
            name='movie_codes',
            field=database.models.CharListField(default=['', '', '', '', '', '', '', '', '', '', '']),
        ),
        migrations.AddField(
            model_name='score',
            name='time3',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
